FrontendServices/InsureApp/Models/ErrorViewModel.cs
namespace InsureApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FrontendServices/InsureApp/Models/MemberModel.cs
using System.ComponentModel.DataAnnotations;

namespace InsureApp.web.Models
{
    public class MemberModel
    {
        public int  MemberId { get; set; }  // Assuming this will be auto-generated, no validation needed

        //[Required(ErrorMessage = "Name name is required.")]
        //[StringLength(50, ErrorMessage = "Name cannot be longer than 50 characters.")]
        //public string Name { get; set; }

        //[Required(ErrorMessage = "Age is required.")]        
        //public int  Age { get; set; }

        //[Required(ErrorMessage = "Date of birth  is required.")]        
        //public DateOnly DateOfBirth { get; set; }

        //[Required(ErrorMessage = "Occupation is required.")]       
        //public string Occupation { get; set; }

        //[Required(ErrorMessage = "SumInsured is required.")]        
        //public decimal SumInsured  { get; set; }


        public int Id { get; set; }
        [StringLength(50, ErrorMessage = "Name cannot be longer than 50 characters.")]
        public string Name { get; set; }

        public DateOnly DateOfBirth { get; set; }
        [Required(ErrorMessage = "Age is required.")]
        public byte AgeNextBirthDay { get; set; }

        public int OccupationId { get; set; }
        [Required(ErrorMessage = "SumInsured is required.")]
        public decimal SumInsured { get; set; }        

        public decimal? MonthlyPremium { get; set; } 
    }
}

FrontendServices/InsureApp/Models/OccupationModel.cs
namespace InsureApp.web.Models
{
    public class OccupationModel
    {
        public int Id { get; set; }

        public string Occupation { get; set; }

        public string Rating { get; set; }
    }
}

FrontendServices/InsureApp/Controllers/HomeController.cs
using InsureApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InsureApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult PremiumCalculation()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FrontendServices/InsureApp/Controllers/PremiumCalculationController.cs
using InsureApp.Controllers;
using InsureApp.web.HttpClients;
using InsureApp.web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace InsureApp.web.Controllers
{
    public class PremiumCalculationController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly PremiumCalculationServiceClient _premiumCalculationServiceClient;
        public PremiumCalculationController( PremiumCalculationServiceClient premiumCalculationServiceClient,ILogger<HomeController> logger)
        {
            _logger = logger;
            _premiumCalculationServiceClient = premiumCalculationServiceClient;
        }

        public IActionResult CalculatePremium()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CalculatePremiumAsync(MemberModel model)
        {
            if(ModelState.IsValid)
            {
                try
                {
                    //var response = _premiumCalculationServiceClient.GetPremiumAsync(model).Result;
                    //ViewBag.Premium = premium;

                    var responseModels = await _premiumCalculationServiceClient.GetPremiumAsync(model);

                    if (responseModels != null)
                    {

                        model.MonthlyPremium = responseModels.MonthlyPremium;
                    }
                    else
                    {
                        throw new Exception("Error calculating premium: Returned member data is null.");
                    }
                    // var products = await _catalogServiceClient.GetProducts();
                    // return View(model);
                    //return RedirectToAction( "DisplayPremium", "PremiumCalculation");                    
                }
                catch(Exception ex)
                {
                    _logger.LogError("Error calculating premium: {Message}", ex.Message);
                    ModelState.AddModelError(string.Empty, "An error occurred while calculating the premium. Please try again later.");
                }
            }

            return View(model);
        }

        public IActionResult DisplayPremium()
        {
            return View();
        }
    }
}

FrontendServices/InsureApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FrontendServices/InsureApp/Views/PremiumCalculation/CalculatePremium.cshtml
@model InsureApp.web.Models.MemberModel


@{
    ViewData["Title"] = "PremiumCalculator";
}

<h1>Premium Calculator</h1>

<h4>Member Details</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CalculatePremium">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MemberId" class="control-label"></label>
                <input asp-for="MemberId" class="form-control" />
                <span asp-validation-for="MemberId" class=""></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgeNextBirthDay" class="control-label"></label>
                <input asp-for="AgeNextBirthDay" class="form-control" />
                <span asp-validation-for="AgeNextBirthDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OccupationId" class="control-label"></label>
                <input asp-for="OccupationId" class="form-control" />
                <span asp-validation-for="OccupationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SumInsured" class="control-label"></label>
                <input asp-for="SumInsured" class="form-control" />
                <span asp-validation-for="SumInsured" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Calculate" class="btn btn-primary" />
            </div>
        </form>

        @if (Model != null && Model.MonthlyPremium > 0)
        {
            <div> <h3>Monthly Premium: @Model.MonthlyPremium.ToString()$</h3></div>
        }

       @*  <div>
            <label>Monthly Premium</label>
            <span class="col-sm-10">
                <b>@ViewBag.Premium</b>
             </span>
        </div> *@
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FrontendServices/InsureApp/Views/PremiumCalculation/DisplayPremium.cshtml
@model InsureApp.web.Models.MemberModel

@{
    ViewData["Title"] = "DisplayPremium";
}

<h1>DisplayPremium</h1>

<div>
    <h4>MemberModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MemberId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MemberId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgeNextBirthDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgeNextBirthDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OccupationId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OccupationId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SumInsured)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SumInsured)
        </dd>
        <dt class="col-sm-2">
            Monthly Premium
        </dt>
        <dd class="col-sm-10">
            <b>@ViewBag.Premium</b>
        </dd>
    </dl>
</div>
<div>
    @* @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) | *@
    <a asp-action="Index">Back to List</a>
</div>

FrontendServices/InsureApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InsureApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InsureApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InsureApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PremiumCalculation" asp-action="CalculatePremium">Calculate Premium</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - InsureApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>